### ISSUE TITLE
Fix naming conventions of current problem examlples

### ISSUE THREAD

**Issue by f-fromont** [HiruNya/Parsons-Tool#85]
- use underscores instead of camelcase for functions
- rename variables to be more useful as well

**Comment by HiruNya** [comment]
Can be considered completed once we merge in the changes in #91 and populate the db

**Comment by HiruNya** [comment]
Fixed by #91

**Comment by HiruNya** [comment]
I just realised that the `arr` in insertion sort could fall under this.
